# Generated by Django 5.0.1 on 2025-12-14 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_option', models.CharField(choices=[('purchaser', 'Send the gift voucher to my email address'), ('recipient', "Send the gift voucher to recipient's email address")], max_length=20, verbose_name='Email Delivery Option')),
                ('recipient_name', models.CharField(max_length=200, verbose_name='Recipient Name')),
                ('personalised_message', models.TextField(blank=True, verbose_name='Personalised Message')),
                ('from_name', models.CharField(max_length=200, verbose_name='Who is this gift from?')),
                ('purchaser_first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('purchaser_last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('purchaser_email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('purchaser_mobile', models.CharField(max_length=20, verbose_name='Mobile Number')),
                ('recipient_email', models.EmailField(blank=True, max_length=254, verbose_name='Recipient Email Address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False, verbose_name='Email Sent')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gift_vouchers', to='treatments.treatment')),
            ],
            options={
                'verbose_name': 'Gift Voucher',
                'verbose_name_plural': 'Gift Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
