# Generated by Django 5.0.1 on 2025-12-14 22:29

import blogs.models
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_hr', models.CharField(max_length=200, verbose_name='Title (Croatian)')),
                ('slug_hr', models.SlugField(max_length=200, unique=True, verbose_name='Slug (Croatian)')),
                ('short_description_hr', models.TextField(max_length=500, verbose_name='Short Description (Croatian)')),
                ('full_description_hr', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Full Description (Croatian)')),
                ('title_en', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('slug_en', models.SlugField(max_length=200, unique=True, verbose_name='Slug (English)')),
                ('short_description_en', models.TextField(max_length=500, verbose_name='Short Description (English)')),
                ('full_description_en', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Full Description (English)')),
                ('thumbnail', models.ImageField(help_text='Supports WebP format', upload_to=blogs.models.blog_thumbnail_upload_path, verbose_name='Thumbnail Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
