# Generated by Django 5.0.1 on 2025-12-17 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description_en',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (English)'),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_description_hr',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (Croatian)'),
        ),
    ]
