# Generated by Django 5.0.1 on 2026-07-22 12:17

import django.utils.timezone
from django.db import migrations, models


def backfill_publish_date(apps, schema_editor):
    Blog = apps.get_model("blogs", "Blog")
    for blog in Blog.objects.all().only("id", "created_at", "publish_date").iterator():
        if blog.created_at:
            Blog.objects.filter(pk=blog.pk).update(publish_date=blog.created_at.date())


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0007_restore_croatian_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="blog",
            options={
                "ordering": ("-publish_date", "-created_at"),
                "verbose_name": "Blog",
                "verbose_name_plural": "Blogs",
            },
        ),
        migrations.AddField(
            model_name="blog",
            name="publish_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="Publish date",
            ),
        ),
        migrations.RunPython(backfill_publish_date, migrations.RunPython.noop),
    ]
