# Generated by Django 5.0.1 on 2025-12-18 17:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatment',
            name='pause_hours',
            field=models.PositiveIntegerField(default=0, help_text='Rest time needed after this treatment (not visible to users)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pause After Treatment (Hours)'),
        ),
        migrations.AddField(
            model_name='treatment',
            name='pause_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Rest time needed after this treatment (not visible to users)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Pause After Treatment (Minutes)'),
        ),
    ]
