# Generated by Django 5.0.1 on 2026-07-18 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0006_remove_converted_ckeditor_fields'),
        ('seo', '0002_migrate_legacy_meta_descriptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='treatment',
            name='meta_description_en',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='meta_description_sr',
        ),
    ]
