# Generated by Django 5.0.1 on 2026-07-22 12:17

import django.utils.timezone
from django.db import migrations, models


def backfill_publish_date(apps, schema_editor):
    Treatment = apps.get_model("treatments", "Treatment")
    for item in Treatment.objects.all().only("id", "created_at", "publish_date").iterator():
        if item.created_at:
            Treatment.objects.filter(pk=item.pk).update(publish_date=item.created_at.date())


class Migration(migrations.Migration):

    dependencies = [
        ("treatments", "0008_restore_croatian_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="treatment",
            options={
                "ordering": ("-publish_date", "-created_at"),
                "verbose_name": "Treatment",
                "verbose_name_plural": "Treatments",
            },
        ),
        migrations.AddField(
            model_name="treatment",
            name="publish_date",
            field=models.DateField(
                default=django.utils.timezone.localdate,
                verbose_name="Publish date",
            ),
        ),
        migrations.RunPython(backfill_publish_date, migrations.RunPython.noop),
    ]
