# Generated by Django 5.0.1 on 2026-07-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0002_rename_hr_fields_to_sr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='full_description_sr',
            field=models.TextField(verbose_name='Full Description (Serbian)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='meta_description_sr',
            field=models.CharField(blank=True, max_length=160, verbose_name='Meta Description (Serbian)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='short_description_sr',
            field=models.TextField(max_length=500, verbose_name='Short Description (Serbian)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='slug_sr',
            field=models.SlugField(max_length=200, unique=True, verbose_name='Slug (Serbian)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='title_sr',
            field=models.CharField(max_length=200, verbose_name='Title (Serbian)'),
        ),
    ]
