# Generated by Django 5.0.1 on 2026-07-18 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0003_update_serbian_verbose_names'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ('-created_at',), 'verbose_name': 'Education', 'verbose_name_plural': 'Education'},
        ),
        migrations.RemoveField(
            model_name='education',
            name='full_description_en',
        ),
        migrations.RemoveField(
            model_name='education',
            name='full_description_sr',
        ),
        migrations.AddField(
            model_name='education',
            name='body_page_en',
            field=models.JSONField(blank=True, null=True, verbose_name='Visual content (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='body_page_sr',
            field=models.JSONField(blank=True, null=True, verbose_name='Visual content (Serbian)'),
        ),
        migrations.AddField(
            model_name='education',
            name='body_plaintext_en',
            field=models.TextField(blank=True, editable=False, verbose_name='Plaintext content (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='body_plaintext_sr',
            field=models.TextField(blank=True, editable=False, verbose_name='Plaintext content (Serbian)'),
        ),
        migrations.AddField(
            model_name='education',
            name='page_version_en',
            field=models.PositiveIntegerField(default=0, verbose_name='Content version (English)'),
        ),
        migrations.AddField(
            model_name='education',
            name='page_version_sr',
            field=models.PositiveIntegerField(default=0, verbose_name='Content version (Serbian)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=500, verbose_name='Short Description (English)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='short_description_sr',
            field=models.TextField(blank=True, max_length=500, verbose_name='Short Description (Serbian)'),
        ),
        migrations.AlterField(
            model_name='education',
            name='thumbnail',
            field=models.ImageField(blank=True, help_text='Supports WebP format', upload_to='content/featured/%Y/%m/', verbose_name='Thumbnail Image'),
        ),
    ]
