# Generated by Django 5.0.1 on 2026-07-18 11:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeoMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField(verbose_name='object ID')),
                ('locale', models.CharField(choices=[('sr', 'Serbian'), ('en', 'English')], max_length=12, verbose_name='language')),
                ('seo_title', models.CharField(blank=True, max_length=200, verbose_name='SEO title')),
                ('meta_description', models.TextField(blank=True, max_length=320, verbose_name='meta description')),
                ('focus_keyword', models.CharField(blank=True, max_length=120, verbose_name='focus keyword')),
                ('secondary_keywords', models.CharField(blank=True, help_text='Separate keywords with commas.', max_length=500, verbose_name='secondary keywords')),
                ('canonical_url', models.URLField(blank=True, verbose_name='canonical URL')),
                ('robots_index', models.BooleanField(default=True, verbose_name='allow indexing')),
                ('robots_follow', models.BooleanField(default=True, verbose_name='follow links')),
                ('robots_nosnippet', models.BooleanField(default=False, verbose_name='disable search snippets')),
                ('robots_noarchive', models.BooleanField(default=False, verbose_name='disable cached copy')),
                ('robots_max_snippet', models.IntegerField(blank=True, help_text='Leave empty to use the search engine default.', null=True, verbose_name='maximum snippet length')),
                ('robots_max_image_preview', models.CharField(blank=True, choices=[('', 'Default'), ('none', 'No image'), ('standard', 'Standard'), ('large', 'Large')], max_length=12, verbose_name='search-result image preview')),
                ('include_in_sitemap', models.BooleanField(default=True, verbose_name='include in sitemap')),
                ('og_title', models.CharField(blank=True, max_length=200, verbose_name='Open Graph title')),
                ('og_description', models.TextField(blank=True, max_length=320, verbose_name='Open Graph description')),
                ('og_image', models.ImageField(blank=True, upload_to='seo/og/%Y/%m/', verbose_name='Open Graph image')),
                ('og_type', models.CharField(blank=True, default='article', max_length=30, verbose_name='Open Graph type')),
                ('og_url', models.URLField(blank=True, verbose_name='Open Graph URL')),
                ('twitter_title', models.CharField(blank=True, max_length=200, verbose_name='Twitter/X title')),
                ('twitter_description', models.TextField(blank=True, max_length=320, verbose_name='Twitter/X description')),
                ('twitter_image', models.ImageField(blank=True, upload_to='seo/twitter/%Y/%m/', verbose_name='Twitter/X image')),
                ('twitter_card', models.CharField(blank=True, default='summary_large_image', max_length=32, verbose_name='Twitter/X card')),
                ('schema_type', models.CharField(blank=True, default='Article', max_length=40, verbose_name='Schema type')),
                ('breadcrumb_title', models.CharField(blank=True, max_length=200, verbose_name='breadcrumb title')),
                ('is_cornerstone', models.BooleanField(default=False, verbose_name='cornerstone content')),
                ('seo_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='SEO score')),
                ('keyword_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='keyword score')),
                ('readability_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='readability score')),
                ('internal_linking_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='internal-linking score')),
                ('image_seo_score', models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='image SEO score')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='content type')),
            ],
            options={
                'verbose_name': 'SEO metadata',
                'verbose_name_plural': 'SEO metadata',
                'indexes': [models.Index(fields=['content_type', 'object_id', 'locale'], name='seo_seometa_content_b1c604_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='seometadata',
            constraint=models.UniqueConstraint(fields=('content_type', 'object_id', 'locale'), name='seo_unique_object_locale'),
        ),
        migrations.AddConstraint(
            model_name='seometadata',
            constraint=models.CheckConstraint(check=models.Q(('locale__in', ('sr', 'en'))), name='seo_locale_sr_or_en'),
        ),
    ]
