# Generated by Django 5.0.1 on 2026-07-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seo', '0003_restore_croatian_locale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seometadata',
            name='internal_linking_score',
            field=models.PositiveSmallIntegerField(default=0, editable=False, verbose_name='internal linking score'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='robots_max_image_preview',
            field=models.CharField(blank=True, choices=[('', 'Default'), ('none', 'No image'), ('standard', 'Standard'), ('large', 'Large')], max_length=12, verbose_name='image preview in results'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='robots_max_snippet',
            field=models.IntegerField(blank=True, help_text='Leave empty to let the search engine use its default length.', null=True, verbose_name='max snippet length'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='robots_noarchive',
            field=models.BooleanField(default=False, verbose_name='no cached copy'),
        ),
        migrations.AlterField(
            model_name='seometadata',
            name='robots_nosnippet',
            field=models.BooleanField(default=False, verbose_name='no snippet in results'),
        ),
    ]
